### ISSUE TITLE
Error message when using 1.0.* version in a .NET Core project

### ISSUE THREAD

**Issue by comdw** [laser-cake/AssemblyVersionLoader#1]
Hi,

Extension proved very useful for me on a .NET Framework build, but now also trying on a .NET Core project and get the following:

```
2018-06-01T15:20:23.1990324Z Loaded assembly file 'MyAssembly, Version=1.0.6726.27600, Culture=neutral, PublicKeyToken=null'
2018-06-01T15:20:23.1990515Z 
2018-06-01T15:20:23.1991288Z 
2018-06-01T15:20:23.7862404Z ##[error]System.Management.Automation.RuntimeException: Cannot convert value "1.0.*" to type "System.Version". Error: "Input string was not in a correct format." ---> System.Management.Automation.PSInvalidCastException: Cannot convert value "1.0.*" to type "System.Version". Error: "Input string was not in a correct format." ---> System.FormatException: Input string was not in a correct format.
2018-06-01T15:20:23.7871872Z    at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
2018-06-01T15:20:23.7872064Z    at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
2018-06-01T15:20:23.7872752Z    at System.Version.TryParseVersion(String version, VersionResult& result)
2018-06-01T15:20:23.7872869Z    at System.Version.Parse(String input)
2018-06-01T15:20:23.7872981Z    --- End of inner exception stack trace ---
2018-06-01T15:20:23.7873127Z    at System.Management.Automation.LanguagePrimitives.ConvertViaParseMethod.ConvertWithoutCulture(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
2018-06-01T15:20:23.7873448Z    at CallSite.Target(Closure , CallSite , Object )
2018-06-01T15:20:23.7873716Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
2018-06-01T15:20:23.7874493Z    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
2018-06-01T15:20:23.7874655Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-06-01T15:20:23.7874821Z    --- End of inner exception stack trace ---
2018-06-01T15:20:23.8188965Z Setting variable AssemblyInfo.Name to 'CICDTest.Container'
2018-06-01T15:20:23.8189303Z 
2018-06-01T15:20:23.8189457Z 
2018-06-01T15:20:23.8482045Z Setting variable AssemblyInfo.AssemblyVersion to '1.0.6726.27600'
2018-06-01T15:20:23.8482347Z 
2018-06-01T15:20:23.8482456Z 
2018-06-01T15:20:23.8496001Z Setting variable AssemblyInfo.AssemblyVersion.Major to '1'
2018-06-01T15:20:23.8496345Z 
2018-06-01T15:20:23.8496524Z 
2018-06-01T15:20:23.8515151Z Setting variable AssemblyInfo.AssemblyVersion.Minor to '0'
2018-06-01T15:20:23.8515495Z 
2018-06-01T15:20:23.8515697Z 
2018-06-01T15:20:23.8535412Z Setting variable AssemblyInfo.AssemblyVersion.Build to '6726'
2018-06-01T15:20:23.8535759Z 
2018-06-01T15:20:23.8535955Z 
2018-06-01T15:20:23.8554921Z Setting variable AssemblyInfo.AssemblyVersion.Revision to '27600'
2018-06-01T15:20:23.8555333Z 
2018-06-01T15:20:23.8555502Z 
2018-06-01T15:20:23.8560242Z Setting variable AssemblyInfo.FileVersion to ''
2018-06-01T15:20:23.8560536Z 
2018-06-01T15:20:23.8562506Z 
2018-06-01T15:20:23.9005894Z Setting variable AssemblyInfo.FileVersion.Major to ''
2018-06-01T15:20:23.9006239Z 
2018-06-01T15:20:23.9006398Z 
2018-06-01T15:20:23.9022080Z Setting variable AssemblyInfo.FileVersion.Minor to ''
2018-06-01T15:20:23.9022602Z 
2018-06-01T15:20:23.9022739Z 
2018-06-01T15:20:23.9037768Z Setting variable AssemblyInfo.FileVersion.Build to ''
2018-06-01T15:20:23.9038004Z 
2018-06-01T15:20:23.9038128Z 
2018-06-01T15:20:23.9053584Z Setting variable AssemblyInfo.FileVersion.Revision to ''
2018-06-01T15:20:23.9054071Z 
2018-06-01T15:20:23.9054230Z 
2018-06-01T15:20:24.0137653Z ##[error]PowerShell script completed with 1 errors.
```

The logs after the exception message seem to indicate that the information I need is available regardless.

In the project I'm using this setting in the .csproj:

`<AssemblyVersion>1.0.*</AssemblyVersion>` which translates to a generated assembly version at build time like 1.0.6726.27600 in the DLL so it seems like the extension is trying to also read the value from the .csproj and not just the DLL.

Side note:  any plans to support this on the Linux hosted agent?

**Comment by AppiePau** [comment]
Hi, you are exactly describing the issue that I was running into with the full native framework and decided to read the compiled dll file.  No the script is not reading the project file as far as I'm aware of. The given DLL file is loaded by the Assembly class using the Powershell available classes.

My first guess is that '1.0.*' written into the file as the file version and thus not replaced at compile time. Does it show when opening the file properties could you check it out with a hex editor (eg opening the file in Visual Studio)?

I'd like to fiddle with it in my spare time to see what's happening, but no guarantees. Feel free to clone of fork.

**Comment by comdw** [comment]
Thanks for the tip to load the DLL into VS.  I could then see that the FileVersion was being set to 1.0.*

I can work around this issue by adding `<FileVersion>1.0.0.0</FileVersion>`, but it seems in .NET Core there is no way to get the FileVersion to be something like 1.0.xxxx.xxxxx for now.

Next issue is my build uses the linux agent to build a docker container and this extension doesn't currently for in linux.  Not sure what's involved there.  I might be able to split my build into seperate agent phases but its a bit cumbersome.

**Comment by AppiePau** [comment]
You’re welcome. Yes, I guess Core has a differen approach to processing file versions. 

I have been so blunt to copy the Powershell script from another extension and utilize the provided .NET API that comes with PS. I guess the same can apply to a Linux extension using bash scripts. I have no experience with that.

You may like to look into the possibility of installing Poweshell on Linux though: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6

Out of curiosity, what are you using the extension for?

**Comment by comdw** [comment]
I'm using it to determine a version number for a docker image built in a later step.  I also use a different extension to rename the VSTS build to the generated assembly version.  I'm finding VSTS's inability to provide a semver compatible build number per project frustrating and this is one of the options I'm exploring.
